name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install -g aws-cdk@1.x
          pip install -r SourceCode/requirements.txt

      - name: TestIntegration
        run: pytest SourceCode/aws_cdk_serverless_test/integration
